create table if not exists public.rol (
  id integer generated by default as identity primary key,
  name varchar not null,
  description text
);

comment on table public.rol is 'Roles disponibles para perfiles de usuario.';
comment on column public.rol.name is 'Nombre visible del rol.';
comment on column public.rol.description is 'Descripcion funcional del rol.';

create unique index if not exists rol_name_key on public.rol (name);

create table if not exists public.profile_rol (
  rol_id integer not null references public.rol(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  date_start date not null,
  date_end date,

  constraint profile_rol_pkey primary key (rol_id, user_id, date_start),
  constraint profile_rol_date_range_check check (
    date_end is null
    or date_end >= date_start
  )
);

comment on table public.profile_rol is 'Asignacion temporal de roles a perfiles de usuario.';
comment on column public.profile_rol.rol_id is 'Rol asignado al perfil.';
comment on column public.profile_rol.user_id is 'Perfil al que se asigna el rol.';
comment on column public.profile_rol.date_start is 'Fecha de inicio de la asignacion.';
comment on column public.profile_rol.date_end is 'Fecha de fin de la asignacion. Null indica que no caduca.';

create index if not exists profile_rol_user_id_idx on public.profile_rol (user_id);
create index if not exists profile_rol_rol_id_idx on public.profile_rol (rol_id);

insert into public.rol (name, description)
values
  ('Usuario', 'Usuario estandar de la aplicacion.'),
  ('Admin', 'Administrador de la aplicacion.'),
  ('Master', 'Director o responsable de partida.')
on conflict (name) do update
set description = excluded.description;

alter table public.profiles
  add column if not exists name varchar;

comment on column public.profiles.name is 'Nombre visible del perfil.';

drop policy if exists "Authenticated users can delete dice rolls" on public.dice_rolls;
create policy "Authenticated users can delete dice rolls"
on public.dice_rolls
for delete
to authenticated
using (
  exists (
    select 1
    from public.profile_rol pr
    join public.rol r on r.id = pr.rol_id
    where pr.user_id = auth.uid()
      and (pr.date_end is null or pr.date_end >= current_date)
      and lower(r.name) in ('admin', 'master')
  )
);
