create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profile_rol pr
    join public.rol r on r.id = pr.rol_id
    where pr.user_id = auth.uid()
      and (pr.date_end is null or pr.date_end >= current_date)
      and lower(r.name) = 'admin'
  );
$$;

create table if not exists public.language (
  id integer generated by default as identity primary key,
  name varchar not null
);

comment on table public.language is 'Idiomas disponibles para traducciones.';
comment on column public.language.name is 'Nombre visible del idioma.';

create unique index if not exists language_name_key on public.language (name);

insert into public.language (id, name)
values
  (1, U&'Espa\00F1ol'),
  (2, 'English')
on conflict (id) do update
set name = excluded.name;

select setval(
  pg_get_serial_sequence('public.language', 'id'),
  greatest((select max(id) from public.language), 1),
  true
);

create table if not exists public.lancer_glossary_tipo (
  id integer generated by default as identity primary key,
  name varchar not null,
  color varchar not null,

  constraint lancer_glossary_tipo_color_hex_check check (
    color ~ '^#[0-9A-Fa-f]{6}$'
  )
);

comment on table public.lancer_glossary_tipo is 'Tipos disponibles para entradas del glosario Lancer.';
comment on column public.lancer_glossary_tipo.name is 'Nombre visible del tipo.';
comment on column public.lancer_glossary_tipo.color is 'Color hexadecimal asociado al tipo.';

create unique index if not exists lancer_glossary_tipo_name_key
on public.lancer_glossary_tipo (name);

create table if not exists public.lancer_glossary (
  id integer generated by default as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  type_id integer not null references public.lancer_glossary_tipo(id) on delete restrict,
  date date not null default current_date
);

comment on table public.lancer_glossary is 'Entradas base del glosario Lancer.';
comment on column public.lancer_glossary.user_id is 'Perfil propietario de la entrada.';
comment on column public.lancer_glossary.type_id is 'Tipo de entrada del glosario.';
comment on column public.lancer_glossary.date is 'Fecha de la entrada.';

create index if not exists lancer_glossary_user_id_idx
on public.lancer_glossary (user_id);

create index if not exists lancer_glossary_type_id_idx
on public.lancer_glossary (type_id);

create index if not exists lancer_glossary_date_idx
on public.lancer_glossary (date desc);

create table if not exists public.lancer_glossary_translation (
  glossary_id integer not null references public.lancer_glossary(id) on delete cascade,
  language_id integer not null references public.language(id) on delete restrict,
  name varchar not null,
  description text,

  constraint lancer_glossary_translation_pkey primary key (glossary_id, language_id)
);

comment on table public.lancer_glossary_translation is 'Traducciones de entradas del glosario Lancer por idioma.';
comment on column public.lancer_glossary_translation.name is 'Nombre traducido de la entrada.';
comment on column public.lancer_glossary_translation.description is 'Descripcion larga traducida de la entrada.';

create index if not exists lancer_glossary_translation_language_id_idx
on public.lancer_glossary_translation (language_id);

alter table public.language enable row level security;
alter table public.lancer_glossary_tipo enable row level security;
alter table public.lancer_glossary enable row level security;
alter table public.lancer_glossary_translation enable row level security;

revoke all on table public.language from anon;
revoke all on table public.language from authenticated;
revoke all on table public.lancer_glossary_tipo from anon;
revoke all on table public.lancer_glossary_tipo from authenticated;
revoke all on table public.lancer_glossary from anon;
revoke all on table public.lancer_glossary from authenticated;
revoke all on table public.lancer_glossary_translation from anon;
revoke all on table public.lancer_glossary_translation from authenticated;

grant select on table public.language to authenticated;
grant select on table public.lancer_glossary_tipo to anon, authenticated;
grant select on table public.lancer_glossary to anon, authenticated;
grant select on table public.lancer_glossary_translation to anon, authenticated;

grant insert, update, delete on table public.language to authenticated;
grant insert, update, delete on table public.lancer_glossary_tipo to authenticated;
grant insert, update, delete on table public.lancer_glossary to authenticated;
grant insert, update, delete on table public.lancer_glossary_translation to authenticated;

grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Authenticated users can read languages" on public.language;
create policy "Authenticated users can read languages"
on public.language
for select
to authenticated
using (auth.uid() is not null);

drop policy if exists "Admins can insert languages" on public.language;
create policy "Admins can insert languages"
on public.language
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update languages" on public.language;
create policy "Admins can update languages"
on public.language
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete languages" on public.language;
create policy "Admins can delete languages"
on public.language
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read lancer glossary types" on public.lancer_glossary_tipo;
create policy "Anyone can read lancer glossary types"
on public.lancer_glossary_tipo
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert lancer glossary types" on public.lancer_glossary_tipo;
create policy "Admins can insert lancer glossary types"
on public.lancer_glossary_tipo
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update lancer glossary types" on public.lancer_glossary_tipo;
create policy "Admins can update lancer glossary types"
on public.lancer_glossary_tipo
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete lancer glossary types" on public.lancer_glossary_tipo;
create policy "Admins can delete lancer glossary types"
on public.lancer_glossary_tipo
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read lancer glossary" on public.lancer_glossary;
create policy "Anyone can read lancer glossary"
on public.lancer_glossary
for select
to anon, authenticated
using (true);

drop policy if exists "Owners and admins can insert lancer glossary" on public.lancer_glossary;
create policy "Owners and admins can insert lancer glossary"
on public.lancer_glossary
for insert
to authenticated
with check (
  auth.uid() is not null
  and (user_id = auth.uid() or public.is_admin())
);

drop policy if exists "Owners and admins can update lancer glossary" on public.lancer_glossary;
create policy "Owners and admins can update lancer glossary"
on public.lancer_glossary
for update
to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

drop policy if exists "Owners and admins can delete lancer glossary" on public.lancer_glossary;
create policy "Owners and admins can delete lancer glossary"
on public.lancer_glossary
for delete
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Anyone can read lancer glossary translations" on public.lancer_glossary_translation;
create policy "Anyone can read lancer glossary translations"
on public.lancer_glossary_translation
for select
to anon, authenticated
using (true);

drop policy if exists "Owners and admins can insert lancer glossary translations" on public.lancer_glossary_translation;
create policy "Owners and admins can insert lancer glossary translations"
on public.lancer_glossary_translation
for insert
to authenticated
with check (
  exists (
    select 1
    from public.lancer_glossary lg
    where lg.id = glossary_id
      and (lg.user_id = auth.uid() or public.is_admin())
  )
);

drop policy if exists "Owners and admins can update lancer glossary translations" on public.lancer_glossary_translation;
create policy "Owners and admins can update lancer glossary translations"
on public.lancer_glossary_translation
for update
to authenticated
using (
  exists (
    select 1
    from public.lancer_glossary lg
    where lg.id = glossary_id
      and (lg.user_id = auth.uid() or public.is_admin())
  )
)
with check (
  exists (
    select 1
    from public.lancer_glossary lg
    where lg.id = glossary_id
      and (lg.user_id = auth.uid() or public.is_admin())
  )
);

drop policy if exists "Owners and admins can delete lancer glossary translations" on public.lancer_glossary_translation;
create policy "Owners and admins can delete lancer glossary translations"
on public.lancer_glossary_translation
for delete
to authenticated
using (
  exists (
    select 1
    from public.lancer_glossary lg
    where lg.id = glossary_id
      and (lg.user_id = auth.uid() or public.is_admin())
  )
);
